# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class Unet(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(Unet, self).__init__()
        self.module_0 = py_nndct.nn.Input() #Unet::input_0(Unet::nndct_input_0)
        self.module_1 = py_nndct.nn.Conv2d(in_channels=4, out_channels=32, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/Conv2dNormActivation[features]/Conv2dNormActivation[0]/Conv2d[0]/ret.11(Unet::nndct_conv2d_1)
        self.module_2 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/Conv2dNormActivation[features]/Conv2dNormActivation[0]/ReLU[2]/13218(Unet::nndct_relu_2)
        self.module_3 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=32, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[1]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.15(Unet::nndct_depthwise_conv2d_3)
        self.module_4 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[1]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13246(Unet::nndct_relu_4)
        self.module_5 = py_nndct.nn.Conv2d(in_channels=32, out_channels=16, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[1]/Sequential[conv]/Conv2d[1]/ret.19(Unet::nndct_conv2d_5)
        self.module_6 = py_nndct.nn.Conv2d(in_channels=16, out_channels=96, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[2]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.23(Unet::nndct_conv2d_6)
        self.module_7 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[2]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13301(Unet::nndct_relu_7)
        self.module_8 = py_nndct.nn.Conv2d(in_channels=96, out_channels=96, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=96, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[2]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.27(Unet::nndct_depthwise_conv2d_8)
        self.module_9 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[2]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/13329(Unet::nndct_relu_9)
        self.module_10 = py_nndct.nn.Conv2d(in_channels=96, out_channels=24, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[2]/Sequential[conv]/Conv2d[2]/ret.31(Unet::nndct_conv2d_10)
        self.module_11 = py_nndct.nn.Conv2d(in_channels=24, out_channels=144, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[3]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.35(Unet::nndct_conv2d_11)
        self.module_12 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[3]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13384(Unet::nndct_relu_12)
        self.module_13 = py_nndct.nn.Conv2d(in_channels=144, out_channels=144, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=144, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[3]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.39(Unet::nndct_depthwise_conv2d_13)
        self.module_14 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[3]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/13412(Unet::nndct_relu_14)
        self.module_15 = py_nndct.nn.Conv2d(in_channels=144, out_channels=24, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[3]/Sequential[conv]/Conv2d[2]/ret.43(Unet::nndct_conv2d_15)
        self.module_16 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[3]/ret.47(Unet::nndct_elemwise_add_16)
        self.module_17 = py_nndct.nn.Conv2d(in_channels=24, out_channels=144, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[4]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.49(Unet::nndct_conv2d_17)
        self.module_18 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[4]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13470(Unet::nndct_relu_18)
        self.module_19 = py_nndct.nn.Conv2d(in_channels=144, out_channels=144, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=144, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[4]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.53(Unet::nndct_depthwise_conv2d_19)
        self.module_20 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[4]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/13498(Unet::nndct_relu_20)
        self.module_21 = py_nndct.nn.Conv2d(in_channels=144, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[4]/Sequential[conv]/Conv2d[2]/ret.57(Unet::nndct_conv2d_21)
        self.module_22 = py_nndct.nn.Conv2d(in_channels=32, out_channels=192, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[5]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.61(Unet::nndct_conv2d_22)
        self.module_23 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[5]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13553(Unet::nndct_relu_23)
        self.module_24 = py_nndct.nn.Conv2d(in_channels=192, out_channels=192, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=192, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[5]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.65(Unet::nndct_depthwise_conv2d_24)
        self.module_25 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[5]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/13581(Unet::nndct_relu_25)
        self.module_26 = py_nndct.nn.Conv2d(in_channels=192, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[5]/Sequential[conv]/Conv2d[2]/ret.69(Unet::nndct_conv2d_26)
        self.module_27 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[5]/ret.73(Unet::nndct_elemwise_add_27)
        self.module_28 = py_nndct.nn.Conv2d(in_channels=32, out_channels=192, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[6]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.75(Unet::nndct_conv2d_28)
        self.module_29 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[6]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13639(Unet::nndct_relu_29)
        self.module_30 = py_nndct.nn.Conv2d(in_channels=192, out_channels=192, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=192, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[6]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.79(Unet::nndct_depthwise_conv2d_30)
        self.module_31 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[6]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/13667(Unet::nndct_relu_31)
        self.module_32 = py_nndct.nn.Conv2d(in_channels=192, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[6]/Sequential[conv]/Conv2d[2]/ret.83(Unet::nndct_conv2d_32)
        self.module_33 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[6]/ret.87(Unet::nndct_elemwise_add_33)
        self.module_34 = py_nndct.nn.Conv2d(in_channels=32, out_channels=192, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[7]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.89(Unet::nndct_conv2d_34)
        self.module_35 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[7]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13725(Unet::nndct_relu_35)
        self.module_36 = py_nndct.nn.Conv2d(in_channels=192, out_channels=192, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=192, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[7]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.93(Unet::nndct_depthwise_conv2d_36)
        self.module_37 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[7]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/13753(Unet::nndct_relu_37)
        self.module_38 = py_nndct.nn.Conv2d(in_channels=192, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[7]/Sequential[conv]/Conv2d[2]/ret.97(Unet::nndct_conv2d_38)
        self.module_39 = py_nndct.nn.Conv2d(in_channels=64, out_channels=384, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[8]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.101(Unet::nndct_conv2d_39)
        self.module_40 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[8]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13808(Unet::nndct_relu_40)
        self.module_41 = py_nndct.nn.Conv2d(in_channels=384, out_channels=384, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=384, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[8]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.105(Unet::nndct_depthwise_conv2d_41)
        self.module_42 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[8]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/13836(Unet::nndct_relu_42)
        self.module_43 = py_nndct.nn.Conv2d(in_channels=384, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[8]/Sequential[conv]/Conv2d[2]/ret.109(Unet::nndct_conv2d_43)
        self.module_44 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[8]/ret.113(Unet::nndct_elemwise_add_44)
        self.module_45 = py_nndct.nn.Conv2d(in_channels=64, out_channels=384, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[9]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.115(Unet::nndct_conv2d_45)
        self.module_46 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[9]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13894(Unet::nndct_relu_46)
        self.module_47 = py_nndct.nn.Conv2d(in_channels=384, out_channels=384, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=384, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[9]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.119(Unet::nndct_depthwise_conv2d_47)
        self.module_48 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[9]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/13922(Unet::nndct_relu_48)
        self.module_49 = py_nndct.nn.Conv2d(in_channels=384, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[9]/Sequential[conv]/Conv2d[2]/ret.123(Unet::nndct_conv2d_49)
        self.module_50 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[9]/ret.127(Unet::nndct_elemwise_add_50)
        self.module_51 = py_nndct.nn.Conv2d(in_channels=64, out_channels=384, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[10]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.129(Unet::nndct_conv2d_51)
        self.module_52 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[10]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/13980(Unet::nndct_relu_52)
        self.module_53 = py_nndct.nn.Conv2d(in_channels=384, out_channels=384, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=384, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[10]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.133(Unet::nndct_depthwise_conv2d_53)
        self.module_54 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[10]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/14008(Unet::nndct_relu_54)
        self.module_55 = py_nndct.nn.Conv2d(in_channels=384, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[10]/Sequential[conv]/Conv2d[2]/ret.137(Unet::nndct_conv2d_55)
        self.module_56 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[10]/ret.141(Unet::nndct_elemwise_add_56)
        self.module_57 = py_nndct.nn.Conv2d(in_channels=64, out_channels=384, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[11]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.143(Unet::nndct_conv2d_57)
        self.module_58 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[11]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/14066(Unet::nndct_relu_58)
        self.module_59 = py_nndct.nn.Conv2d(in_channels=384, out_channels=384, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=384, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[11]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.147(Unet::nndct_depthwise_conv2d_59)
        self.module_60 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[11]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/14094(Unet::nndct_relu_60)
        self.module_61 = py_nndct.nn.Conv2d(in_channels=384, out_channels=96, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[11]/Sequential[conv]/Conv2d[2]/ret.151(Unet::nndct_conv2d_61)
        self.module_62 = py_nndct.nn.Conv2d(in_channels=96, out_channels=576, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[12]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.155(Unet::nndct_conv2d_62)
        self.module_63 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[12]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/14149(Unet::nndct_relu_63)
        self.module_64 = py_nndct.nn.Conv2d(in_channels=576, out_channels=576, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=576, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[12]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.159(Unet::nndct_depthwise_conv2d_64)
        self.module_65 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[12]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/14177(Unet::nndct_relu_65)
        self.module_66 = py_nndct.nn.Conv2d(in_channels=576, out_channels=96, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[12]/Sequential[conv]/Conv2d[2]/ret.163(Unet::nndct_conv2d_66)
        self.module_67 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[12]/ret.167(Unet::nndct_elemwise_add_67)
        self.module_68 = py_nndct.nn.Conv2d(in_channels=96, out_channels=576, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[13]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.169(Unet::nndct_conv2d_68)
        self.module_69 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[13]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/14235(Unet::nndct_relu_69)
        self.module_70 = py_nndct.nn.Conv2d(in_channels=576, out_channels=576, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=576, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[13]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.173(Unet::nndct_depthwise_conv2d_70)
        self.module_71 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[13]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/14263(Unet::nndct_relu_71)
        self.module_72 = py_nndct.nn.Conv2d(in_channels=576, out_channels=96, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[13]/Sequential[conv]/Conv2d[2]/ret.177(Unet::nndct_conv2d_72)
        self.module_73 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[13]/ret.181(Unet::nndct_elemwise_add_73)
        self.module_74 = py_nndct.nn.Conv2d(in_channels=96, out_channels=576, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[14]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.183(Unet::nndct_conv2d_74)
        self.module_75 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[14]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/14321(Unet::nndct_relu_75)
        self.module_76 = py_nndct.nn.Conv2d(in_channels=576, out_channels=576, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=576, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[14]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.187(Unet::nndct_depthwise_conv2d_76)
        self.module_77 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[14]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/14349(Unet::nndct_relu_77)
        self.module_78 = py_nndct.nn.Conv2d(in_channels=576, out_channels=160, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[14]/Sequential[conv]/Conv2d[2]/ret.191(Unet::nndct_conv2d_78)
        self.module_79 = py_nndct.nn.Conv2d(in_channels=160, out_channels=960, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[15]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.195(Unet::nndct_conv2d_79)
        self.module_80 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[15]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/14404(Unet::nndct_relu_80)
        self.module_81 = py_nndct.nn.Conv2d(in_channels=960, out_channels=960, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=960, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[15]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.199(Unet::nndct_depthwise_conv2d_81)
        self.module_82 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[15]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/14432(Unet::nndct_relu_82)
        self.module_83 = py_nndct.nn.Conv2d(in_channels=960, out_channels=160, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[15]/Sequential[conv]/Conv2d[2]/ret.203(Unet::nndct_conv2d_83)
        self.module_84 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[15]/ret.207(Unet::nndct_elemwise_add_84)
        self.module_85 = py_nndct.nn.Conv2d(in_channels=160, out_channels=960, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[16]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.209(Unet::nndct_conv2d_85)
        self.module_86 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[16]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/14490(Unet::nndct_relu_86)
        self.module_87 = py_nndct.nn.Conv2d(in_channels=960, out_channels=960, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=960, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[16]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.213(Unet::nndct_depthwise_conv2d_87)
        self.module_88 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[16]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/14518(Unet::nndct_relu_88)
        self.module_89 = py_nndct.nn.Conv2d(in_channels=960, out_channels=160, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[16]/Sequential[conv]/Conv2d[2]/ret.217(Unet::nndct_conv2d_89)
        self.module_90 = py_nndct.nn.Add() #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[16]/ret.221(Unet::nndct_elemwise_add_90)
        self.module_91 = py_nndct.nn.Conv2d(in_channels=160, out_channels=960, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[17]/Sequential[conv]/Conv2dNormActivation[0]/Conv2d[0]/ret.223(Unet::nndct_conv2d_91)
        self.module_92 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[17]/Sequential[conv]/Conv2dNormActivation[0]/ReLU[2]/14576(Unet::nndct_relu_92)
        self.module_93 = py_nndct.nn.Conv2d(in_channels=960, out_channels=960, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=960, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[17]/Sequential[conv]/Conv2dNormActivation[1]/Conv2d[0]/ret.227(Unet::nndct_depthwise_conv2d_93)
        self.module_94 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[17]/Sequential[conv]/Conv2dNormActivation[1]/ReLU[2]/14604(Unet::nndct_relu_94)
        self.module_95 = py_nndct.nn.Conv2d(in_channels=960, out_channels=320, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/InvertedResidual[features]/InvertedResidual[17]/Sequential[conv]/Conv2d[2]/ret.231(Unet::nndct_conv2d_95)
        self.module_96 = py_nndct.nn.Conv2d(in_channels=320, out_channels=1280, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/MobileNetV2Encoder[encoder]/Conv2dNormActivation[features]/Conv2dNormActivation[18]/Conv2d[0]/ret.235(Unet::nndct_conv2d_96)
        self.module_97 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/MobileNetV2Encoder[encoder]/Conv2dNormActivation[features]/Conv2dNormActivation[18]/ReLU[2]/14659(Unet::nndct_relu_97)
        self.module_98 = py_nndct.nn.Interpolate() #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[0]/ret.239(Unet::nndct_resize_98)
        self.module_99 = py_nndct.nn.Cat() #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[0]/ret.241(Unet::nndct_concat_99)
        self.module_100 = py_nndct.nn.Conv2d(in_channels=1376, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[0]/Conv2dReLU[conv1]/Conv2d[0]/ret.243(Unet::nndct_conv2d_100)
        self.module_101 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[0]/Conv2dReLU[conv1]/ReLU[2]/14706(Unet::nndct_relu_101)
        self.module_102 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[0]/Conv2dReLU[conv2]/Conv2d[0]/ret.247(Unet::nndct_conv2d_102)
        self.module_103 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[0]/Conv2dReLU[conv2]/ReLU[2]/14734(Unet::nndct_relu_103)
        self.module_104 = py_nndct.nn.Interpolate() #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[1]/ret.251(Unet::nndct_resize_104)
        self.module_105 = py_nndct.nn.Cat() #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[1]/ret.253(Unet::nndct_concat_105)
        self.module_106 = py_nndct.nn.Conv2d(in_channels=288, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[1]/Conv2dReLU[conv1]/Conv2d[0]/ret.255(Unet::nndct_conv2d_106)
        self.module_107 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[1]/Conv2dReLU[conv1]/ReLU[2]/14776(Unet::nndct_relu_107)
        self.module_108 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[1]/Conv2dReLU[conv2]/Conv2d[0]/ret.259(Unet::nndct_conv2d_108)
        self.module_109 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[1]/Conv2dReLU[conv2]/ReLU[2]/14804(Unet::nndct_relu_109)
        self.module_110 = py_nndct.nn.Interpolate() #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[2]/ret.263(Unet::nndct_resize_110)
        self.module_111 = py_nndct.nn.Cat() #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[2]/ret.265(Unet::nndct_concat_111)
        self.module_112 = py_nndct.nn.Conv2d(in_channels=152, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[2]/Conv2dReLU[conv1]/Conv2d[0]/ret.267(Unet::nndct_conv2d_112)
        self.module_113 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[2]/Conv2dReLU[conv1]/ReLU[2]/14846(Unet::nndct_relu_113)
        self.module_114 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[2]/Conv2dReLU[conv2]/Conv2d[0]/ret.271(Unet::nndct_conv2d_114)
        self.module_115 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[2]/Conv2dReLU[conv2]/ReLU[2]/14874(Unet::nndct_relu_115)
        self.module_116 = py_nndct.nn.Interpolate() #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[3]/ret.275(Unet::nndct_resize_116)
        self.module_117 = py_nndct.nn.Cat() #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[3]/ret.277(Unet::nndct_concat_117)
        self.module_118 = py_nndct.nn.Conv2d(in_channels=80, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[3]/Conv2dReLU[conv1]/Conv2d[0]/ret.279(Unet::nndct_conv2d_118)
        self.module_119 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[3]/Conv2dReLU[conv1]/ReLU[2]/14916(Unet::nndct_relu_119)
        self.module_120 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[3]/Conv2dReLU[conv2]/Conv2d[0]/ret.283(Unet::nndct_conv2d_120)
        self.module_121 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[3]/Conv2dReLU[conv2]/ReLU[2]/14944(Unet::nndct_relu_121)
        self.module_122 = py_nndct.nn.Interpolate() #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[4]/ret.287(Unet::nndct_resize_122)
        self.module_123 = py_nndct.nn.Conv2d(in_channels=32, out_channels=16, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[4]/Conv2dReLU[conv1]/Conv2d[0]/ret.289(Unet::nndct_conv2d_123)
        self.module_124 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[4]/Conv2dReLU[conv1]/ReLU[2]/14980(Unet::nndct_relu_124)
        self.module_125 = py_nndct.nn.Conv2d(in_channels=16, out_channels=16, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[4]/Conv2dReLU[conv2]/Conv2d[0]/ret.293(Unet::nndct_conv2d_125)
        self.module_126 = py_nndct.nn.ReLU(inplace=True) #Unet::Unet/UnetDecoder[decoder]/DecoderBlock[blocks]/ModuleList[4]/Conv2dReLU[conv2]/ReLU[2]/15008(Unet::nndct_relu_126)
        self.module_127 = py_nndct.nn.Conv2d(in_channels=16, out_channels=1, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #Unet::Unet/SegmentationHead[segmentation_head]/Conv2d[0]/ret(Unet::nndct_conv2d_127)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_0 = self.module_5(output_module_0)
        output_module_6 = self.module_6(output_module_0)
        output_module_6 = self.module_7(output_module_6)
        output_module_6 = self.module_8(output_module_6)
        output_module_6 = self.module_9(output_module_6)
        output_module_6 = self.module_10(output_module_6)
        output_module_11 = self.module_11(output_module_6)
        output_module_11 = self.module_12(output_module_11)
        output_module_11 = self.module_13(output_module_11)
        output_module_11 = self.module_14(output_module_11)
        output_module_11 = self.module_15(output_module_11)
        output_module_16 = self.module_16(input=output_module_6, other=output_module_11, alpha=1)
        output_module_17 = self.module_17(output_module_16)
        output_module_17 = self.module_18(output_module_17)
        output_module_17 = self.module_19(output_module_17)
        output_module_17 = self.module_20(output_module_17)
        output_module_17 = self.module_21(output_module_17)
        output_module_22 = self.module_22(output_module_17)
        output_module_22 = self.module_23(output_module_22)
        output_module_22 = self.module_24(output_module_22)
        output_module_22 = self.module_25(output_module_22)
        output_module_22 = self.module_26(output_module_22)
        output_module_27 = self.module_27(input=output_module_17, other=output_module_22, alpha=1)
        output_module_28 = self.module_28(output_module_27)
        output_module_28 = self.module_29(output_module_28)
        output_module_28 = self.module_30(output_module_28)
        output_module_28 = self.module_31(output_module_28)
        output_module_28 = self.module_32(output_module_28)
        output_module_33 = self.module_33(input=output_module_27, other=output_module_28, alpha=1)
        output_module_34 = self.module_34(output_module_33)
        output_module_34 = self.module_35(output_module_34)
        output_module_34 = self.module_36(output_module_34)
        output_module_34 = self.module_37(output_module_34)
        output_module_34 = self.module_38(output_module_34)
        output_module_39 = self.module_39(output_module_34)
        output_module_39 = self.module_40(output_module_39)
        output_module_39 = self.module_41(output_module_39)
        output_module_39 = self.module_42(output_module_39)
        output_module_39 = self.module_43(output_module_39)
        output_module_44 = self.module_44(input=output_module_34, other=output_module_39, alpha=1)
        output_module_45 = self.module_45(output_module_44)
        output_module_45 = self.module_46(output_module_45)
        output_module_45 = self.module_47(output_module_45)
        output_module_45 = self.module_48(output_module_45)
        output_module_45 = self.module_49(output_module_45)
        output_module_50 = self.module_50(input=output_module_44, other=output_module_45, alpha=1)
        output_module_51 = self.module_51(output_module_50)
        output_module_51 = self.module_52(output_module_51)
        output_module_51 = self.module_53(output_module_51)
        output_module_51 = self.module_54(output_module_51)
        output_module_51 = self.module_55(output_module_51)
        output_module_56 = self.module_56(input=output_module_50, other=output_module_51, alpha=1)
        output_module_56 = self.module_57(output_module_56)
        output_module_56 = self.module_58(output_module_56)
        output_module_56 = self.module_59(output_module_56)
        output_module_56 = self.module_60(output_module_56)
        output_module_56 = self.module_61(output_module_56)
        output_module_62 = self.module_62(output_module_56)
        output_module_62 = self.module_63(output_module_62)
        output_module_62 = self.module_64(output_module_62)
        output_module_62 = self.module_65(output_module_62)
        output_module_62 = self.module_66(output_module_62)
        output_module_67 = self.module_67(input=output_module_56, other=output_module_62, alpha=1)
        output_module_68 = self.module_68(output_module_67)
        output_module_68 = self.module_69(output_module_68)
        output_module_68 = self.module_70(output_module_68)
        output_module_68 = self.module_71(output_module_68)
        output_module_68 = self.module_72(output_module_68)
        output_module_73 = self.module_73(input=output_module_67, other=output_module_68, alpha=1)
        output_module_74 = self.module_74(output_module_73)
        output_module_74 = self.module_75(output_module_74)
        output_module_74 = self.module_76(output_module_74)
        output_module_74 = self.module_77(output_module_74)
        output_module_74 = self.module_78(output_module_74)
        output_module_79 = self.module_79(output_module_74)
        output_module_79 = self.module_80(output_module_79)
        output_module_79 = self.module_81(output_module_79)
        output_module_79 = self.module_82(output_module_79)
        output_module_79 = self.module_83(output_module_79)
        output_module_84 = self.module_84(input=output_module_74, other=output_module_79, alpha=1)
        output_module_85 = self.module_85(output_module_84)
        output_module_85 = self.module_86(output_module_85)
        output_module_85 = self.module_87(output_module_85)
        output_module_85 = self.module_88(output_module_85)
        output_module_85 = self.module_89(output_module_85)
        output_module_90 = self.module_90(input=output_module_84, other=output_module_85, alpha=1)
        output_module_90 = self.module_91(output_module_90)
        output_module_90 = self.module_92(output_module_90)
        output_module_90 = self.module_93(output_module_90)
        output_module_90 = self.module_94(output_module_90)
        output_module_90 = self.module_95(output_module_90)
        output_module_90 = self.module_96(output_module_90)
        output_module_90 = self.module_97(output_module_90)
        output_module_90 = self.module_98(input=output_module_90, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_90 = self.module_99(dim=1, tensors=[output_module_90,output_module_73])
        output_module_90 = self.module_100(output_module_90)
        output_module_90 = self.module_101(output_module_90)
        output_module_90 = self.module_102(output_module_90)
        output_module_90 = self.module_103(output_module_90)
        output_module_90 = self.module_104(input=output_module_90, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_90 = self.module_105(dim=1, tensors=[output_module_90,output_module_33])
        output_module_90 = self.module_106(output_module_90)
        output_module_90 = self.module_107(output_module_90)
        output_module_90 = self.module_108(output_module_90)
        output_module_90 = self.module_109(output_module_90)
        output_module_90 = self.module_110(input=output_module_90, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_90 = self.module_111(dim=1, tensors=[output_module_90,output_module_16])
        output_module_90 = self.module_112(output_module_90)
        output_module_90 = self.module_113(output_module_90)
        output_module_90 = self.module_114(output_module_90)
        output_module_90 = self.module_115(output_module_90)
        output_module_90 = self.module_116(input=output_module_90, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_90 = self.module_117(dim=1, tensors=[output_module_90,output_module_0])
        output_module_90 = self.module_118(output_module_90)
        output_module_90 = self.module_119(output_module_90)
        output_module_90 = self.module_120(output_module_90)
        output_module_90 = self.module_121(output_module_90)
        output_module_90 = self.module_122(input=output_module_90, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_90 = self.module_123(output_module_90)
        output_module_90 = self.module_124(output_module_90)
        output_module_90 = self.module_125(output_module_90)
        output_module_90 = self.module_126(output_module_90)
        output_module_90 = self.module_127(output_module_90)
        return output_module_90
